# GitHub Actions workflow to build using the Makefile
name: Build Fonts

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Publish release with latest build artifacts?'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.upload-1.outputs.artifact-id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install FontForge
        run: sudo apt-get update && sudo apt-get install -y fontforge

      - name: Install LuaJIT
        run: sudo apt-get install -y luajit

      - name: Build without characters
        run: make without-characters

      - name: Build with characters
        run: make with-characters

      - name: Upload font artifacts without symbol patch
        id: upload-1
        uses: actions/upload-artifact@v4
        with:
          name: OvertureCode.zip
          path: fonts/output

      - name: Upload artifacts (with symbol patch)
        uses: actions/upload-artifact@v4
        with:
          name: OvertureCodeWithCharacterPatch.zip
          path: fonts/output-with-characters
