# GitHub Actions workflow to build using the Makefile
name: Build Fonts

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Publish release with latest build artifacts?'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.upload-1.outputs.artifact-id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install FontForge
        run: sudo apt-get update && sudo apt-get install -y fontforge

      - name: Install LuaJIT
        run: sudo apt-get install -y luajit

      - name: Build without characters
        run: make without-characters

      - name: Build with characters
        run: make with-characters

      - name: Upload font artifacts without symbol patch
        id: upload-1
        uses: actions/upload-artifact@v4
        with:
          name: OvertureCode.zip
          path: fonts/output

      - name: Upload artifacts (with symbol patch)
        uses: actions/upload-artifact@v4
        with:
          name: OvertureCodeWithCharacterPatch.zip
          path: fonts/output-with-characters

  release:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download OvertureCode.zip
        uses: actions/download-artifact@v4
        with:
          name: OvertureCode.zip
          path: fonts/output

      - name: Download OvertureCodeWithCharacterPatch.zip
        uses: actions/download-artifact@v4
        with:
          name: OvertureCodeWithCharacterPatch.zip
          path: fonts/output-with-characters
      
      - name: Repack fonts
        run: |
          cd fonts/output
          zip -r OvertureCode.zip *
          mv OvertureCode.zip ../../
          cd ../output-with-characters
          zip -r OvertureCodeWithCharacterPatch.zip *
          mv OvertureCodeWithCharacterPatch.zip ../../

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release of ligaturized fonts.
          files: |
            OvertureCode.zip
            OvertureCodeWithCharacterPatch.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
