name: Release Fonts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag name'
        required: true
      name:
        description: 'Release name'
        required: false
      body:
        description: 'Release notes/body'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Download OvertureCode.zip
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_search: true
          workflow_conclusion: success
          skip_unpack: true
          allow_forks: false
          name: OvertureCode.zip

      - name: Download OvertureCodeWithCharacterPatch.zip
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          workflow_search: true
          workflow_conclusion: success
          skip_unpack: true
          allow_forks: false
          name: OvertureCodeWithCharacterPatch.zip
    
      - name: Fix filenames
        run: |
          mv OvertureCode.zip.zip OvertureCode.zip
          mv OvertureCodeWithCharacterPatch.zip.zip OvertureCodeWithCharacterPatch.zip

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.name || format('Release {0}', github.event.inputs.tag) }}
          body: ${{ github.event.inputs.body || 'Automated release of ligaturized fonts.' }}
          files: |
            OvertureCode.zip
            OvertureCodeWithCharacterPatch.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
