name: Release Fonts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag name'
        required: true
      name:
        description: 'Release name'
        required: false
      body:
        description: 'Release notes/body'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest successful build run
        id: find_run
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              status: 'success',
              per_page: 1
            });
            if (!runs.data.workflow_runs.length) throw new Error('No successful build runs found.');
            return runs.data.workflow_runs[0].id;
          result-encoding: string

      - name: Download OvertureCode.zip
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          run_id: ${{ steps.find_run.outputs.result }}
          name: OvertureCode.zip

      - name: Download OvertureCodeWithCharacterPatch.zip
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          run_id: ${{ steps.find_run.outputs.result }}
          name: OvertureCodeWithCharacterPatch.zip

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.name || format('Release %s', github.event.inputs.tag) }}
          body: ${{ github.event.inputs.body || 'Automated release of ligaturized fonts.' }}
          files: |
            OvertureCode.zip
            OvertureCodeWithCharacterPatch.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
